// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsProd.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjlOPoz5wY4T4hqLT0L8eJExcB-S66qI',
    appId: '1:235770040244:web:d2bf591c1e7cfc11892ce1',
    messagingSenderId: '235770040244',
    projectId: 'healthstride-prod-8686b',
    authDomain: 'healthstride-prod-8686b.firebaseapp.com',
    storageBucket: 'healthstride-prod-8686b.firebasestorage.app',
    measurementId: 'G-8DPG3S2HFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpr5rqXhCJB_qMLao2xHUKU7GDa7qVEk',
    appId: '1:235770040244:android:074a428502d70f73892ce1',
    messagingSenderId: '235770040244',
    projectId: 'healthstride-prod-8686b',
    storageBucket: 'healthstride-prod-8686b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdrw7nIH4o0YJnY9i6Ug2aecruV2LdgEY',
    appId: '1:235770040244:ios:97c01f70511d5080892ce1',
    messagingSenderId: '235770040244',
    projectId: 'healthstride-prod-8686b',
    storageBucket: 'healthstride-prod-8686b.firebasestorage.app',
    iosBundleId: 'com.healthstride.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdrw7nIH4o0YJnY9i6Ug2aecruV2LdgEY',
    appId: '1:235770040244:ios:97c01f70511d5080892ce1',
    messagingSenderId: '235770040244',
    projectId: 'healthstride-prod-8686b',
    storageBucket: 'healthstride-prod-8686b.firebasestorage.app',
    iosBundleId: 'com.healthstride.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmjlOPoz5wY4T4hqLT0L8eJExcB-S66qI',
    appId: '1:235770040244:web:63b8c4ce0c78146f892ce1',
    messagingSenderId: '235770040244',
    projectId: 'healthstride-prod-8686b',
    authDomain: 'healthstride-prod-8686b.firebaseapp.com',
    storageBucket: 'healthstride-prod-8686b.firebasestorage.app',
    measurementId: 'G-LJ2WKDZ983',
  );
}
