// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsDev.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFV4ZIi8lHKwnqujXvgvJIBzTns6zk6BE',
    appId: '1:412128374578:web:93ff4779e2a49ec2cf312b',
    messagingSenderId: '412128374578',
    projectId: 'healthstride-dev-acad5',
    authDomain: 'healthstride-dev-acad5.firebaseapp.com',
    storageBucket: 'healthstride-dev-acad5.firebasestorage.app',
    measurementId: 'G-X5SQS791S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwjuFHWtPwQLPyBoxk7ALJwiF8gzGVy8',
    appId: '1:412128374578:android:f7d0b9ead33a60adcf312b',
    messagingSenderId: '412128374578',
    projectId: 'healthstride-dev-acad5',
    storageBucket: 'healthstride-dev-acad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjn---uiatQtEKZAiAU-c9FfTSJ2KqywY',
    appId: '1:412128374578:ios:0ca1e2d0ff99bdc1cf312b',
    messagingSenderId: '412128374578',
    projectId: 'healthstride-dev-acad5',
    storageBucket: 'healthstride-dev-acad5.firebasestorage.app',
    iosBundleId: 'com.healthstride.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjn---uiatQtEKZAiAU-c9FfTSJ2KqywY',
    appId: '1:412128374578:ios:f7923c93899aed5ccf312b',
    messagingSenderId: '412128374578',
    projectId: 'healthstride-dev-acad5',
    storageBucket: 'healthstride-dev-acad5.firebasestorage.app',
    iosBundleId: 'com.healthstride.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFV4ZIi8lHKwnqujXvgvJIBzTns6zk6BE',
    appId: '1:412128374578:web:31c57a9a9eb31436cf312b',
    messagingSenderId: '412128374578',
    projectId: 'healthstride-dev-acad5',
    authDomain: 'healthstride-dev-acad5.firebaseapp.com',
    storageBucket: 'healthstride-dev-acad5.firebasestorage.app',
    measurementId: 'G-84WCHZHFWR',
  );
}
